### ISSUE TITLE
Plugin dies on startup

### ISSUE THREAD

**Issue by benjumanji** [sonots/fluent-plugin-named_pipe#5]
I don't know enough ruby to say what this means, but I'd really appreciate any insight you could offer.

os: fedora 25
```
[fedora@concourse-worker-3 ~]$ uname -a
Linux concourse-worker-3.novalocal 4.8.6-300.fc25.x86_64 #1 SMP Tue Nov 1 12:36:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

versions:
```
fluent-plugin-named_pipe (0.1.2)
fluentd (0.12.37)
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

config
```
<source>
  @type named_pipe
  path /run/concourse/fluent.pipe
  tag concourse
  format json
</source>

<match concourse>
  @type stdout
</match>
```

stack trace
```
[fedora@concourse-worker-3 ~]$ fluentd -c ./fluent/test.conf -v
2017-07-06 23:47:36 +0000 [info]: fluent/supervisor.rb:471:read_config: reading config file path="./fluent/test.conf"
2017-07-06 23:47:36 +0000 [info]: fluent/supervisor.rb:337:supervise: starting fluentd-0.12.37
2017-07-06 23:47:36 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-named_pipe' version '0.1.2'
2017-07-06 23:47:36 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-systemd' version '0.2.0'
2017-07-06 23:47:36 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluentd' version '0.12.37'
2017-07-06 23:47:36 +0000 [info]: fluent/agent.rb:129:add_match: adding match pattern="concourse" type="stdout"
2017-07-06 23:47:36 +0000 [info]: fluent/root_agent.rb:152:add_source: adding source type="named_pipe"
2017-07-06 23:47:36 +0000 [error]: fluent/supervisor.rb:369:rescue in main_process: config error file="./fluent/test.conf" error="NoMethodError: undefined method `method_defined?' for #<Fifo:0x0055d162416368 @pipe=#<File:/run/concourse/fluent.pipe>>\nDid you mean?  method_missing"
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluent-plugin-named_pipe-0.1.2/lib/fluent/plugin/in_named_pipe.rb:25:in `rescue in configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluent-plugin-named_pipe-0.1.2/lib/fluent/plugin/in_named_pipe.rb:21:in `configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:159:in `add_source'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:95:in `block in configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:92:in `each'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:92:in `configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/engine.rb:129:in `configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/engine.rb:103:in `run_configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:489:in `run_configure'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:160:in `block in start'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:366:in `main_process'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:339:in `block in supervise'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:338:in `fork'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:338:in `supervise'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:156:in `start'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/.gem/ruby/gems/fluentd-0.12.37/bin/fluentd:5:in `<top (required)>'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/bin/fluentd:22:in `load'
2017-07-06 23:47:36 +0000 [debug]: fluent/supervisor.rb:338:fork: /home/fedora/bin/fluentd:22:in `<main>'
2017-07-06 23:47:36 +0000 [info]: fluent/supervisor.rb:354:supervise: process finished code=256
2017-07-06 23:47:36 +0000 [warn]: fluent/supervisor.rb:357:supervise: process died within 1 second. exit.
```

**Comment by sonots** [comment]
I am not clear about this problem, but please try 0.2.0
